version: '3.5'
services:
  django_app:
    build: .
    ports:
      - "8080:8081"
    depends_on:
      - database
  database:
    image: postgres:15.4
    env_file:
      - database.env
    ports:
      - "6543:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
volumes:
  database-data: 